sonar.projectName=trend-app 

sonar.verbose=true 
sonar.organization=personal 

sonar.projectKey=tweet-trend 
sonar.host.url=http://localhost:9001 
sonar.language=java
sonar.login=sqp_de6c2c7dde9aa09f95372bbff3fdc021882cf214

sonar.projectVersion=1.0
sonar.sources=src,copybooks
sonar.sourceEncoding=UTF-8

sonar.java.binaries =target/classes
sonar.sources = .
sonar.coverage.jacoco.xmlReportPath = target/site/jacoco/jacoco.html


